### ISSUE TITLE
github ci: fix code analysis

### ISSUE THREAD

**Issue by conke** [ooda-system/ooda-course#33]
to remove the 2 commented lines:

```yaml
name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # - name: code analysis
    #   run: grep -w assert `find . -name "*.java"` && false
    - name: install sqlite
      run: sudo apt install -y sqlite3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: project init
      run: src/test/init.sh
    - name: Build with Maven
      run: mvn -Dmaven.test.skip=true package

```
